/**
 * Gerichte-Datenbank des Abendbretts.
 *
 * Neues Gericht ergänzen: eine Zeile im Array EXTRA anlegen.
 *   D(Name, Küche, Kategorie, Minuten, Flags, [Zutaten], Tipp?)
 *   Kategorie: schnell | leicht | komfort | neu | bestellen
 *   Flags:     v = vegetarisch, f = Fleisch, s = Fisch,
 *              k = kalt, p = Vorratskammer, x = scharf
 * Tags werden aus den Flags automatisch erzeugt.
 */

const CORE = [
  { id: 1, name: "Pasta alla Norma", kueche: "Italienisch", cat: "schnell", min: 25,
    veg: true, fleisch: false, kalt: false, vorrat: false, scharf: false,
    tags: ["Vegetarisch", "Ein Topf + Pfanne"],
    zutaten: ["250 g Rigatoni", "1 Aubergine", "400 g stückige Tomaten", "2 Knoblauchzehen", "1 Bund Basilikum", "60 g Feta oder Ricotta salata", "Olivenöl"],
    tipp: "Aubergine großzügig in Öl anbraten – zu wenig Fett macht sie zäh." },

  { id: 2, name: "Zitronen-Risotto mit Erbsen", kueche: "Italienisch", cat: "leicht", min: 35,
    veg: true, fleisch: false, kalt: false, vorrat: false, scharf: false,
    tags: ["Vegetarisch", "Ein Topf"],
    zutaten: ["180 g Risottoreis", "1 Bio-Zitrone", "150 g TK-Erbsen", "1 Schalotte", "100 ml Weißwein", "800 ml Gemüsebrühe", "40 g Parmesan", "1 EL Butter"],
    tipp: "Brühe heiß halten, sonst stoppt die Stärke – und die Butter erst vom Herd unterrühren." },

  { id: 3, name: "Ofen-Gnocchi mit Tomaten & Mozzarella", kueche: "Italienisch", cat: "komfort", min: 30,
    veg: true, fleisch: false, kalt: false, vorrat: false, scharf: false,
    tags: ["Vegetarisch", "Nur ein Blech"],
    zutaten: ["500 g Gnocchi (Kühlregal)", "400 g Kirschtomaten", "1 Zucchini", "125 g Mozzarella", "3 EL Olivenöl", "Oregano", "Salz, Pfeffer"],
    tipp: "Alles roh aufs Blech, 22 Min bei 220 °C. Mozzarella erst die letzten 6 Minuten drauf." },

  { id: 4, name: "Hähnchen-Saltimbocca mit Rosmarinkartoffeln", kueche: "Italienisch", cat: "komfort", min: 35,
    veg: false, fleisch: true, kalt: false, vorrat: false, scharf: false,
    tags: ["Sonntagsgefühl", "Pfanne + Ofen"],
    zutaten: ["2 Hähnchenbrustfilets", "4 Scheiben Parmaschinken", "8 Salbeiblätter", "600 g festkochende Kartoffeln", "2 Zweige Rosmarin", "50 ml Weißwein", "Butter, Olivenöl"],
    tipp: "Kartoffeln zuerst in den Ofen, das Fleisch braucht am Ende nur 8 Minuten." },

  { id: 5, name: "Panzanella mit gegrillter Paprika", kueche: "Mediterran", cat: "leicht", min: 20,
    veg: true, fleisch: false, kalt: true, vorrat: false, scharf: false,
    tags: ["Kalt", "Vegetarisch", "Resteverwertung Brot"],
    zutaten: ["250 g altbackenes Ciabatta", "2 rote Paprika", "400 g Tomaten", "1 rote Zwiebel", "1 Salatgurke", "Rotweinessig", "Olivenöl", "Basilikum"],
    tipp: "Brot 10 Minuten im Dressing ziehen lassen – vorher ist es Salat, danach Panzanella." },

  { id: 6, name: "Orecchiette mit Brokkoli & Sardellen", kueche: "Italienisch", cat: "schnell", min: 25,
    veg: false, fleisch: false, kalt: false, vorrat: true, scharf: true,
    tags: ["Fisch", "Ein Topf", "Vorratskammer"],
    zutaten: ["250 g Orecchiette", "1 Kopf Brokkoli", "4 Sardellenfilets", "2 Knoblauchzehen", "1 Chilischote", "Olivenöl", "Semmelbrösel zum Bestreuen"],
    tipp: "Brokkoli die letzten 5 Minuten zur Pasta ins Wasser – spart einen Topf." },

  { id: 7, name: "Thai-Curry mit Süßkartoffel & Kichererbsen", kueche: "Thai", cat: "komfort", min: 30,
    veg: true, fleisch: false, kalt: false, vorrat: true, scharf: true,
    tags: ["Vegetarisch", "Ein Topf", "Meal-Prep-tauglich"],
    zutaten: ["2 EL rote Currypaste", "400 ml Kokosmilch", "1 große Süßkartoffel", "1 Dose Kichererbsen", "150 g Basmatireis", "1 Limette", "Koriander", "Fischsauce oder Sojasauce"],
    tipp: "Currypaste erst 1 Minute in Öl anrösten – das ist der ganze Unterschied." },

  { id: 8, name: "Gyudon – japanische Rindfleisch-Bowl", kueche: "Japanisch", cat: "neu", min: 25,
    veg: false, fleisch: true, kalt: false, vorrat: false, scharf: false,
    tags: ["Neu ausprobieren", "Eine Pfanne"],
    zutaten: ["300 g dünn geschnittenes Rindfleisch", "2 Zwiebeln", "150 g Sushireis", "4 EL Sojasauce", "3 EL Mirin", "1 TL Zucker", "1 Stück Ingwer", "2 Eier (optional)"],
    tipp: "Rindfleisch beim Metzger hauchdünn schneiden lassen oder angefroren selbst hobeln." },

  { id: 9, name: "Wok-Nudeln mit Hack & Pak Choi", kueche: "Asiatisch", cat: "schnell", min: 20,
    veg: false, fleisch: true, kalt: false, vorrat: false, scharf: true,
    tags: ["Feierabend", "Ein Wok"],
    zutaten: ["250 g Mie-Nudeln", "300 g Hackfleisch", "2 Pak Choi", "3 EL Sojasauce", "1 EL Austernsauce", "1 Knoblauchzehe", "Ingwer", "Sesamöl"],
    tipp: "Wok richtig heiß werden lassen und in zwei Portionen braten, sonst kocht das Hack." },

  { id: 10, name: "Miso-Lachs aus dem Ofen mit Sesamgurken", kueche: "Japanisch", cat: "leicht", min: 25,
    veg: false, fleisch: false, kalt: false, vorrat: false, scharf: false,
    tags: ["Fisch", "Leicht", "Wenig Abwasch"],
    zutaten: ["2 Lachsfilets", "2 EL helles Miso", "1 EL Honig", "1 EL Reisessig", "1 Salatgurke", "1 TL Sesam", "150 g Reis"],
    tipp: "Marinade 10 Minuten einwirken lassen, dann 12 Minuten bei 200 °C – fertig." },

  { id: 11, name: "Mapo Tofu", kueche: "Chinesisch", cat: "neu", min: 25,
    veg: true, fleisch: false, kalt: false, vorrat: true, scharf: true,
    tags: ["Scharf", "Vegetarisch möglich", "Neu ausprobieren"],
    zutaten: ["400 g Seidentofu", "2 EL Doubanjiang (fermentierte Bohnenpaste)", "1 Frühlingszwiebel", "1 Knoblauchzehe", "1 TL Szechuanpfeffer", "1 EL Speisestärke", "150 g Reis"],
    tipp: "Tofu nicht rühren, sondern die Pfanne schwenken – sonst zerfällt er." },

  { id: 12, name: "Sommerrollen mit Erdnusssauce", kueche: "Vietnamesisch", cat: "leicht", min: 30,
    veg: true, fleisch: false, kalt: true, vorrat: false, scharf: false,
    tags: ["Kalt", "Vegetarisch", "Gemeinsam rollen"],
    zutaten: ["12 Reispapierblätter", "100 g Glasnudeln", "1 Karotte", "1 Salatgurke", "Minze & Koriander", "3 EL Erdnussbutter", "2 EL Sojasauce", "1 Limette"],
    tipp: "Reispapier nur kurz ins Wasser tunken – es zieht auf dem Brett von allein nach." },

  { id: 13, name: "Feierabend-Ramen mit Ei & Mais", kueche: "Japanisch", cat: "schnell", min: 20,
    veg: false, fleisch: false, kalt: false, vorrat: true, scharf: false,
    tags: ["Vorratskammer", "Ein Topf", "Komfort"],
    zutaten: ["2 Portionen Ramen-Nudeln", "800 ml Hühnerbrühe", "2 EL Miso", "2 Eier", "1 Dose Mais", "1 Frühlingszwiebel", "Sesamöl", "Nori (optional)"],
    tipp: "Eier exakt 6:30 Min kochen, kalt abschrecken, halbieren – der Dotter bleibt cremig." },

  { id: 14, name: "Kartoffelsalat mit Frikadellen", kueche: "Gutbürgerlich", cat: "komfort", min: 35,
    veg: false, fleisch: true, kalt: false, vorrat: false, scharf: false,
    tags: ["Klassiker", "Reste am nächsten Tag"],
    zutaten: ["800 g festkochende Kartoffeln", "400 g Hackfleisch gemischt", "1 Brötchen", "1 Zwiebel", "1 Ei", "200 ml Brühe", "Essig, Öl, Senf", "Schnittlauch"],
    tipp: "Kartoffeln warm mit der Brühe mischen – kalt saugen sie nichts mehr auf." },

  { id: 15, name: "Bratkartoffeln mit Spiegelei & Gurkensalat", kueche: "Gutbürgerlich", cat: "komfort", min: 30,
    veg: true, fleisch: false, kalt: false, vorrat: true, scharf: false,
    tags: ["Vorratskammer", "Vegetarisch", "Seelenfutter"],
    zutaten: ["800 g gekochte Kartoffeln vom Vortag", "1 Zwiebel", "4 Eier", "1 Salatgurke", "Schmand oder Joghurt", "Butterschmalz", "Dill"],
    tipp: "Kartoffeln 5 Minuten liegen lassen, bevor du wendest – nur so wird die Kruste knusprig." },

  { id: 16, name: "Maultaschen in der Pfanne mit Zwiebelschmelze", kueche: "Schwäbisch", cat: "schnell", min: 20,
    veg: false, fleisch: true, kalt: false, vorrat: true, scharf: false,
    tags: ["Vorratskammer", "Feierabend", "Regional"],
    zutaten: ["6 Maultaschen", "2 Zwiebeln", "2 Eier", "Butter", "Kopfsalat", "Essig, Öl, Senf für das Dressing"],
    tipp: "Maultaschen in Scheiben schneiden und mit dem verquirlten Ei stocken lassen." },

  { id: 17, name: "Schnitzel mit Kartoffel-Gurken-Salat", kueche: "Gutbürgerlich", cat: "komfort", min: 35,
    veg: false, fleisch: true, kalt: false, vorrat: false, scharf: false,
    tags: ["Klassiker", "Etwas Aufwand"],
    zutaten: ["2 Schweineschnitzel", "2 Eier", "100 g Mehl", "150 g Semmelbrösel", "700 g Kartoffeln", "1 Salatgurke", "Butterschmalz", "1 Zitrone"],
    tipp: "Panade nicht andrücken, Pfanne schwenken – dann wird sie soufflierend luftig." },

  { id: 18, name: "Flammkuchen vom Blech", kueche: "Gutbürgerlich", cat: "schnell", min: 25,
    veg: false, fleisch: true, kalt: false, vorrat: false, scharf: false,
    tags: ["Nur ein Blech", "Vegetarisch möglich"],
    zutaten: ["1 Rolle Flammkuchenteig", "200 g Schmand", "150 g Speckwürfel", "2 Zwiebeln", "Muskat, Pfeffer", "Feldsalat als Beilage"],
    tipp: "Ofen auf 250 °C – Flammkuchen braucht Hitze, nicht Zeit. 10 Minuten reichen." },

  { id: 19, name: "Käsespätzle mit Röstzwiebeln", kueche: "Schwäbisch", cat: "komfort", min: 30,
    veg: true, fleisch: false, kalt: false, vorrat: true, scharf: false,
    tags: ["Vegetarisch", "Seelenfutter", "Regional"],
    zutaten: ["500 g Spätzle", "200 g geriebener Bergkäse", "3 Zwiebeln", "Butter", "Blattsalat", "Muskat"],
    tipp: "Schichtweise in die Auflaufform, oberste Lage Käse – 12 Minuten unter den Grill." },

  { id: 20, name: "Melonen-Feta-Salat mit Minze", kueche: "Mediterran", cat: "leicht", min: 15,
    veg: true, fleisch: false, kalt: true, vorrat: false, scharf: false,
    tags: ["Kalt", "Kein Herd", "Für heiße Tage"],
    zutaten: ["1/2 Wassermelone", "200 g Feta", "1 Bund Minze", "1 rote Zwiebel", "Limettensaft", "Olivenöl", "Schwarzer Pfeffer"],
    tipp: "10 Minuten kalt stellen, dann erst salzen – sonst zieht die Melone Wasser." },

  { id: 21, name: "Großer Brotzeit-Teller", kueche: "Gutbürgerlich", cat: "schnell", min: 10,
    veg: false, fleisch: true, kalt: true, vorrat: true, scharf: false,
    tags: ["Kein Herd", "Vorratskammer", "10 Minuten"],
    zutaten: ["1 Laib Bauernbrot", "Käse nach Wahl", "Schinken oder Aufschnitt", "Radieschen", "Butter", "Senf & Essiggurken", "1 Tomate"],
    tipp: "Der ehrlichste Plan-B – schöner Teller, gutes Brot, fertig." },

  { id: 22, name: "Linsen mit Spätzle & Saitenwürstle", kueche: "Schwäbisch", cat: "komfort", min: 40,
    veg: false, fleisch: true, kalt: false, vorrat: true, scharf: false,
    tags: ["Regional", "Meal-Prep-tauglich", "Ein Topf"],
    zutaten: ["250 g Tellerlinsen", "500 g Spätzle", "4 Saitenwürste", "1 Karotte", "1 Zwiebel", "2 EL Essig", "1 EL Mehl für die Schwitze", "Lorbeer"],
    tipp: "Am Ende kräftig mit Essig abschmecken – das trennt gute von langweiligen Linsen." },

  { id: 23, name: "Gebratener Reis mit Ei & Gemüse", kueche: "Chinesisch", cat: "schnell", min: 20,
    veg: true, fleisch: false, kalt: false, vorrat: true, scharf: false,
    tags: ["Vorratskammer", "Resteverwertung", "Ein Wok"],
    zutaten: ["400 g Reis vom Vortag", "3 Eier", "200 g TK-Erbsen & Möhren", "2 Frühlingszwiebeln", "2 EL Sojasauce", "1 TL Sesamöl", "Knoblauch"],
    tipp: "Nur kalter Reis vom Vortag wird körnig. Frischer Reis wird Brei." },

  { id: 24, name: "Bruschetta-Abend mit Antipasti", kueche: "Italienisch", cat: "leicht", min: 15,
    veg: true, fleisch: false, kalt: true, vorrat: false, scharf: false,
    tags: ["Kalt", "Kein Herd", "Zum Teilen"],
    zutaten: ["1 Ciabatta", "500 g reife Tomaten", "1 Knoblauchzehe", "Basilikum", "Oliven & eingelegte Artischocken", "Büffelmozzarella", "gutes Olivenöl"],
    tipp: "Brot rösten, mit roher Knoblauchzehe abreiben – das ist die halbe Miete." },

  /* --- Bestellen --- */
  { id: 30, name: "Pizza vom Italiener", kueche: "Italienisch", cat: "bestellen", min: 0,
    veg: true, fleisch: false, kalt: false, vorrat: true, scharf: false,
    tags: ["Bestellen", "Null Aufwand"],
    zutaten: ["Grüner Salat aus dem Kühlschrank dazu", "Ein Glas Rotwein"],
    tipp: "Eine Pizza mehr bestellen – kalt am nächsten Morgen ist Tradition." },

  { id: 31, name: "Döner oder Falafel", kueche: "Türkisch", cat: "bestellen", min: 0,
    veg: true, fleisch: true, kalt: false, vorrat: true, scharf: true,
    tags: ["Bestellen", "Schnell abgeholt"],
    zutaten: ["Nichts – höchstens Ayran aus dem Kühlschrank"],
    tipp: "Falafel-Variante mit extra Salat, wenn der Abend leicht bleiben soll." },

  { id: 32, name: "Thai-Lieferung", kueche: "Thai", cat: "bestellen", min: 0,
    veg: true, fleisch: true, kalt: false, vorrat: true, scharf: true,
    tags: ["Bestellen", "Zum Teilen"],
    zutaten: ["Zwei Gerichte teilen statt je eins bestellen"],
    tipp: "Pad Thai + ein Curry und beides teilen – reicht meist für drei." },

  { id: 33, name: "Sushi", kueche: "Japanisch", cat: "bestellen", min: 0,
    veg: true, fleisch: false, kalt: true, vorrat: true, scharf: false,
    tags: ["Bestellen", "Leicht"],
    zutaten: ["Edamame und eine Misosuppe dazu"],
    tipp: "Bei Lieferung eher Maki als Nigiri – überlebt den Transport besser." },
];

/* --- kompakte Sammlung: D(Name, Küche, Kategorie, Minuten, Flags, Zutaten, Tipp)
   Flags: v=vegetarisch  f=Fleisch  s=Fisch  k=kalt  p=Vorratskammer  x=scharf --- */
export const D = (name, kueche, cat, min, fl, zutaten, tipp = "") => {
  const f = (c) => fl.includes(c);
  const tags = [];
  if (cat === "bestellen") tags.push("Lieferung");
  if (f("v")) tags.push("Vegetarisch");
  if (f("s")) tags.push("Fisch");
  if (f("k")) tags.push("Kalt");
  if (f("p")) tags.push("Vorratskammer");
  if (f("x")) tags.push("Scharf");
  if (min > 0 && min <= 20) tags.push("Unter 20 Min");
  if (min >= 60) tags.push("Wochenendprojekt");
  return { name, kueche, cat, min, veg: f("v"), fleisch: f("f"),
    kalt: f("k"), vorrat: f("p"), scharf: f("x"), tags, zutaten, tipp };
};

const EXTRA = [
  /* ---------------- Italienisch & Mediterran ---------------- */
  D("Spaghetti Bolognese", "Italienisch", "komfort", 40, "f", ["250 g Spaghetti", "400 g Rinderhack", "1 Karotte", "1 Stange Sellerie", "1 Zwiebel", "700 g passierte Tomaten", "100 ml Rotwein", "Parmesan"], "Je länger sie köchelt, desto besser – 40 Min sind das Minimum."),
  D("Spaghetti mit Meeresfrüchten", "Italienisch", "neu", 30, "s", ["250 g Spaghetti", "400 g TK-Meeresfrüchte", "2 Knoblauchzehen", "1 Chili", "150 ml Weißwein", "Petersilie", "Kirschtomaten"], "Meeresfrüchte nur 3 Minuten – länger und sie werden gummiartig."),
  D("Spaghetti Carbonara", "Italienisch", "schnell", 20, "fp", ["250 g Spaghetti", "150 g Guanciale oder Pancetta", "3 Eigelb", "60 g Pecorino", "Schwarzer Pfeffer"], "Pfanne vom Herd, bevor das Ei dazukommt – sonst gibt es Rührei."),
  D("Spaghetti Aglio e Olio", "Italienisch", "schnell", 15, "vpx", ["250 g Spaghetti", "4 Knoblauchzehen", "1 Chili", "80 ml Olivenöl", "Petersilie"], "Der Klassiker, wenn der Kühlschrank leer ist."),
  D("Penne Arrabbiata", "Italienisch", "schnell", 20, "vpx", ["250 g Penne", "400 g stückige Tomaten", "2 Knoblauchzehen", "2 Chilischoten", "Olivenöl", "Basilikum"]),
  D("Spaghetti Cacio e Pepe", "Italienisch", "schnell", 15, "vp", ["250 g Spaghetti", "100 g Pecorino", "2 TL schwarzer Pfeffer", "Nudelwasser"], "Nudelwasser ist die Soße – unbedingt eine Tasse aufheben."),
  D("Lasagne al Forno", "Italienisch", "komfort", 75, "f", ["12 Lasagneplatten", "500 g Hackfleisch", "700 g passierte Tomaten", "500 ml Milch", "40 g Butter", "40 g Mehl", "150 g geriebener Käse"], "Doppelte Menge machen und eine Form einfrieren."),
  D("Pizza vom Blech", "Italienisch", "komfort", 45, "v", ["400 g Mehl", "1 Päckchen Trockenhefe", "250 ml Wasser", "200 g passierte Tomaten", "250 g Mozzarella", "Belag nach Wahl", "Oregano"], "Ofen auf höchste Stufe und das Blech vorheizen."),
  D("Risotto ai Funghi", "Italienisch", "komfort", 35, "v", ["180 g Risottoreis", "300 g Champignons", "1 Schalotte", "100 ml Weißwein", "800 ml Gemüsebrühe", "Parmesan", "Petersilie"]),
  D("Gnocchi in Salbeibutter", "Italienisch", "schnell", 15, "vp", ["500 g Gnocchi", "60 g Butter", "10 Salbeiblätter", "Parmesan", "Pinienkerne"]),
  D("Tortellini in Sahnesoße", "Italienisch", "schnell", 15, "fp", ["500 g Tortellini", "200 ml Sahne", "100 g Schinkenwürfel", "TK-Erbsen", "Parmesan", "Muskat"]),
  D("Pasta al Pesto mit grünen Bohnen", "Italienisch", "schnell", 20, "vp", ["250 g Trofie oder Penne", "200 g grüne Bohnen", "1 Glas Pesto Genovese", "1 Kartoffel", "Parmesan"]),
  D("Vitello Tonnato", "Italienisch", "leicht", 30, "fk", ["400 g gegartes Kalbfleisch in Scheiben", "1 Dose Thunfisch", "3 EL Mayonnaise", "2 EL Joghurt", "Kapern", "1 Zitrone"]),
  D("Minestrone", "Italienisch", "leicht", 40, "v", ["2 Karotten", "1 Zucchini", "1 Dose weiße Bohnen", "1 Stange Sellerie", "100 g Suppennudeln", "1 l Gemüsebrühe", "Parmesanrinde"]),
  D("Piccata Milanese mit Tomatenspaghetti", "Italienisch", "komfort", 35, "f", ["2 Kalbs- oder Putenschnitzel", "2 Eier", "60 g Parmesan", "250 g Spaghetti", "500 g passierte Tomaten", "Basilikum"]),
  D("Calzone vom Blech", "Italienisch", "komfort", 40, "f", ["1 Pizzateig", "150 g Schinken", "200 g Ricotta", "125 g Mozzarella", "Tomatensoße", "Oregano"]),
  D("Pasta e Fagioli", "Italienisch", "komfort", 35, "vp", ["150 g kurze Pasta", "1 Dose Borlottibohnen", "1 Karotte", "1 Zwiebel", "400 g Tomaten", "Rosmarin"]),
  D("Ofen-Polenta mit Ratatouille", "Italienisch", "leicht", 45, "v", ["200 g Polenta", "1 Aubergine", "1 Zucchini", "2 Paprika", "400 g Tomaten", "Parmesan", "Thymian"]),
  D("Nudelauflauf mit Schinken", "Italienisch", "komfort", 45, "f", ["300 g Penne", "150 g Kochschinken", "400 ml Sahne", "3 Eier", "200 g geriebener Käse", "TK-Erbsen"]),
  D("Tagliatelle mit Lachs & Spinat", "Italienisch", "schnell", 20, "s", ["250 g Tagliatelle", "200 g Lachsfilet", "200 g Blattspinat", "150 ml Sahne", "1 Zitrone", "Knoblauch"]),
  D("Arancini mit Tomatensugo", "Italienisch", "neu", 45, "v", ["Risottoreste oder 200 g Risottoreis", "125 g Mozzarella", "2 Eier", "150 g Semmelbrösel", "Frittieröl", "Tomatensugo"], "Perfekt für Risotto-Reste vom Vortag."),
  D("Focaccia mit Antipasti", "Mediterran", "leicht", 40, "v", ["400 g Mehl", "Trockenhefe", "Olivenöl", "Rosmarin & grobes Salz", "Oliven", "eingelegte Artischocken", "Büffelmozzarella"]),
  D("Caprese mit Ciabatta", "Italienisch", "leicht", 10, "vk", ["3 große Tomaten", "250 g Büffelmozzarella", "Basilikum", "gutes Olivenöl", "1 Ciabatta"]),
  D("Gefüllte Paprika mit Reis und Hack", "Mediterran", "komfort", 60, "f", ["4 Paprika", "400 g Hackfleisch", "150 g Reis", "1 Zwiebel", "400 g passierte Tomaten", "Feta"]),
  D("Ratatouille mit Baguette", "Mediterran", "leicht", 40, "v", ["1 Aubergine", "2 Zucchini", "2 Paprika", "400 g Tomaten", "1 Zwiebel", "Kräuter der Provence", "1 Baguette"]),

  /* ---------------- Gutbürgerlich & Schwäbisch ---------------- */
  D("Fleischkäse mit Spinat und Spiegelei", "Gutbürgerlich", "schnell", 20, "fp", ["4 Scheiben Fleischkäse", "450 g Rahmspinat (TK)", "4 Eier", "600 g Kartoffeln für Püree oder Salzkartoffeln", "Butter", "Muskat"], "Fleischkäse einritzen, dann wellt er sich in der Pfanne nicht."),
  D("Currywurst mit Pommes", "Gutbürgerlich", "schnell", 25, "fpx", ["4 Bratwürste", "600 g TK-Pommes", "200 g Ketchup", "2 EL Tomatenmark", "2 TL Currypulver", "1 TL Paprikapulver", "Prise Zucker"], "Ketchup mit Curry kurz aufkochen – schmeckt sofort nach Bude."),
  D("Rindersteak mit Kräuterbutter und Ofengemüse", "Gutbürgerlich", "komfort", 30, "f", ["2 Rumpsteaks à 250 g", "100 g Butter", "Petersilie & Knoblauch", "2 Paprika", "1 Zucchini", "400 g Kartoffeln", "Rosmarin"], "Steak 30 Min vorher aus dem Kühlschrank, danach 5 Min ruhen lassen."),
  D("Züricher Geschnetzeltes mit Rösti", "Gutbürgerlich", "komfort", 40, "f", ["400 g Kalbs- oder Putengeschnetzeltes", "250 g Champignons", "1 Zwiebel", "200 ml Sahne", "100 ml Weißwein", "700 g Kartoffeln", "Butterschmalz"], "Fleisch scharf anbraten, herausnehmen, erst am Ende zurück in die Soße."),
  D("Hähnchen-Brokkoli-Auflauf", "Gutbürgerlich", "komfort", 45, "f", ["500 g Hähnchenbrust", "1 großer Brokkoli", "600 g Kartoffeln", "250 ml Sahne", "150 g geriebener Käse", "2 EL Senf", "Muskat"], "Kartoffeln vorkochen, sonst bleiben sie im Auflauf bissfest."),
  D("Jägerschnitzel mit Pommes", "Gutbürgerlich", "komfort", 40, "f", ["2 Schweineschnitzel", "250 g Champignons", "200 ml Sahne", "1 Zwiebel", "600 g TK-Pommes", "Paniermehl & Ei"]),
  D("Rahmschnitzel mit Spätzle", "Gutbürgerlich", "komfort", 35, "f", ["2 Schweineschnitzel", "200 ml Sahne", "1 Zwiebel", "500 g Spätzle", "Brühe", "Petersilie"]),
  D("Zwiebelrostbraten mit Spätzle", "Schwäbisch", "komfort", 45, "f", ["2 Rostbraten à 200 g", "3 große Zwiebeln", "500 g Spätzle", "Rotwein", "Rinderfond", "Mehl zum Wenden"]),
  D("Rinderrouladen mit Rotkohl und Klößen", "Gutbürgerlich", "komfort", 120, "f", ["4 Rouladen", "4 Scheiben Speck", "2 Gewürzgurken", "Senf", "1 Glas Rotkohl", "1 Packung Klöße", "Rinderfond"], "Klassiker fürs Wochenende – am nächsten Tag noch besser."),
  D("Gulasch mit Nudeln", "Gutbürgerlich", "komfort", 90, "f", ["700 g Rindergulasch", "4 Zwiebeln", "2 EL Paprikapulver", "1 Dose Tomaten", "Rinderfond", "250 g Bandnudeln"]),
  D("Königsberger Klopse mit Salzkartoffeln", "Gutbürgerlich", "komfort", 50, "f", ["500 g Hackfleisch", "1 Brötchen", "1 Ei", "3 EL Kapern", "200 ml Sahne", "1 Zitrone", "700 g Kartoffeln"]),
  D("Hackbraten mit Kartoffelpüree", "Gutbürgerlich", "komfort", 70, "f", ["600 g Hackfleisch", "2 Brötchen", "2 Eier", "1 Zwiebel", "3 hartgekochte Eier", "800 g Kartoffeln", "Milch & Butter"]),
  D("Sauerkraut mit Bratwurst und Püree", "Gutbürgerlich", "komfort", 35, "fp", ["1 Glas Sauerkraut", "4 Bratwürste", "800 g Kartoffeln", "1 Zwiebel", "Wacholderbeeren", "Milch & Butter"]),
  D("Grünkohl mit Kassler", "Gutbürgerlich", "komfort", 60, "f", ["800 g Grünkohl (TK)", "2 Stück Kassler", "2 Zwiebeln", "Schmalz", "Senf", "Salzkartoffeln"]),
  D("Kartoffelpuffer mit Apfelmus", "Gutbürgerlich", "komfort", 30, "v", ["1 kg Kartoffeln", "1 Zwiebel", "2 Eier", "3 EL Mehl", "Öl zum Braten", "1 Glas Apfelmus"], "Kartoffelmasse gut ausdrücken – Wasser ist der Feind der Kruste."),
  D("Bauernfrühstück", "Gutbürgerlich", "schnell", 25, "fp", ["600 g gekochte Kartoffeln", "150 g Schinkenwürfel", "5 Eier", "1 Zwiebel", "Schnittlauch", "Gewürzgurken"]),
  D("Strammer Max", "Gutbürgerlich", "schnell", 10, "fp", ["4 Scheiben Bauernbrot", "4 Scheiben gekochter Schinken", "4 Eier", "Butter", "Schnittlauch"]),
  D("Wurstsalat mit Brot", "Schwäbisch", "leicht", 10, "fkp", ["300 g Lyoner in Streifen", "1 Zwiebel", "2 Gewürzgurken", "Essig & Öl", "Senf", "1 Laib Brot", "Schnittlauch"]),
  D("Überbackene Toasts Hawaii", "Gutbürgerlich", "schnell", 15, "fp", ["8 Scheiben Toast", "4 Scheiben Schinken", "4 Scheiben Ananas", "4 Scheiben Käse", "Butter"]),
  D("Erbsensuppe mit Bockwurst", "Gutbürgerlich", "komfort", 40, "fp", ["400 g Schälerbsen", "4 Bockwürste", "2 Karotten", "1 Lauch", "300 g Kartoffeln", "Majoran"]),
  D("Kartoffelsuppe mit Würstchen", "Gutbürgerlich", "komfort", 40, "f", ["800 g Kartoffeln", "2 Karotten", "1 Lauch", "4 Wiener", "1 l Brühe", "Majoran", "Schmand"]),
  D("Gemüsesuppe mit Nudeln", "Gutbürgerlich", "leicht", 35, "v", ["1 Bund Suppengemüse", "150 g Suppennudeln", "1,2 l Gemüsebrühe", "Petersilie", "Muskat"]),
  D("Gaisburger Marsch", "Schwäbisch", "komfort", 60, "f", ["500 g Rindfleisch", "300 g Spätzle", "500 g Kartoffeln", "1 Bund Suppengemüse", "2 Zwiebeln", "Petersilie"]),
  D("Schupfnudeln mit Sauerkraut und Speck", "Schwäbisch", "schnell", 20, "fp", ["500 g Schupfnudeln", "1 Glas Sauerkraut", "150 g Speckwürfel", "1 Zwiebel", "Kümmel"]),
  D("Hähnchenschenkel aus dem Ofen", "Gutbürgerlich", "komfort", 55, "f", ["4 Hähnchenschenkel", "800 g Kartoffeln", "2 Zwiebeln", "Paprikapulver", "Olivenöl", "Rosmarin"], "Alles auf ein Blech, 45 Min bei 200 °C – null Aufwand, viel Effekt."),
  D("Putengeschnetzeltes mit Reis", "Gutbürgerlich", "schnell", 25, "f", ["400 g Putengeschnetzeltes", "1 Paprika", "200 ml Sahne", "1 Zwiebel", "150 g Reis", "Curry oder Paprikapulver"]),
  D("Schweinefilet im Speckmantel mit Kartoffelgratin", "Gutbürgerlich", "komfort", 60, "f", ["1 Schweinefilet", "10 Scheiben Bacon", "800 g Kartoffeln", "300 ml Sahne", "150 g Käse", "Knoblauch", "Muskat"]),
  D("Wirsingrouladen", "Gutbürgerlich", "komfort", 60, "f", ["8 Wirsingblätter", "400 g Hackfleisch", "1 Brötchen", "1 Ei", "1 Zwiebel", "Brühe", "Salzkartoffeln"]),
  D("Kartoffelgratin mit Blattsalat", "Gutbürgerlich", "komfort", 60, "v", ["1 kg Kartoffeln", "400 ml Sahne", "150 g Käse", "1 Knoblauchzehe", "Muskat", "Blattsalat"]),
  D("Kartoffel-Hack-Auflauf", "Gutbürgerlich", "komfort", 60, "f", ["800 g Kartoffeln", "400 g Hackfleisch", "1 Zwiebel", "300 ml Sahne", "150 g Käse", "TK-Erbsen"]),
  D("Gemüseauflauf mit Béchamel", "Gutbürgerlich", "komfort", 55, "v", ["1 Brokkoli", "1 Blumenkohl", "600 g Kartoffeln", "500 ml Milch", "40 g Butter", "40 g Mehl", "150 g Käse"]),
  D("Blumenkohl mit Käsesoße und Kartoffeln", "Gutbürgerlich", "komfort", 40, "v", ["1 Blumenkohl", "700 g Kartoffeln", "300 ml Milch", "100 g Bergkäse", "Butter & Mehl", "Muskat", "Semmelbrösel"]),
  D("Ofenkartoffel mit Kräuterquark", "Gutbürgerlich", "komfort", 60, "vp", ["4 große Kartoffeln", "500 g Magerquark", "100 ml Milch", "Schnittlauch & Petersilie", "1 Knoblauchzehe", "Leinöl"]),
  D("Pellkartoffeln mit Leinöl und Quark", "Gutbürgerlich", "schnell", 30, "vp", ["1 kg Kartoffeln", "500 g Quark", "Leinöl", "Zwiebel", "Schnittlauch"]),
  D("Milchreis mit Zimt und Zucker", "Gutbürgerlich", "schnell", 25, "vp", ["200 g Milchreis", "1 l Milch", "2 EL Zucker", "1 Prise Salz", "Zimt", "Kirschen aus dem Glas"]),
  D("Herzhafte Pfannkuchen mit Schinken", "Gutbürgerlich", "schnell", 20, "fp", ["250 g Mehl", "500 ml Milch", "4 Eier", "150 g Schinkenwürfel", "Schnittlauch", "Butterschmalz"]),
  D("Eierkuchen mit Apfelmus", "Gutbürgerlich", "schnell", 20, "vp", ["250 g Mehl", "500 ml Milch", "4 Eier", "1 Prise Salz", "Apfelmus", "Zimtzucker"]),
  D("Fischstäbchen mit Kartoffelsalat", "Gutbürgerlich", "schnell", 25, "sp", ["15 Fischstäbchen", "800 g Kartoffeln", "1 Zwiebel", "Brühe", "Essig & Öl", "Remoulade"]),
  D("Backfisch mit Remoulade", "Gutbürgerlich", "komfort", 35, "s", ["500 g Kabeljaufilet", "150 g Mehl", "200 ml Bier", "Frittieröl", "Remoulade", "Kartoffelsalat", "1 Zitrone"]),
  D("Matjes mit Bratkartoffeln", "Gutbürgerlich", "leicht", 30, "s", ["4 Matjesfilets", "800 g gekochte Kartoffeln", "1 Zwiebel", "1 Apfel", "200 g Schmand", "Dill"]),
  D("Nudelsalat mit Wurst und Erbsen", "Gutbürgerlich", "leicht", 30, "fk", ["300 g Nudeln", "200 g Fleischwurst", "1 Dose Erbsen", "3 Gewürzgurken", "Mayonnaise & Joghurt", "Senf"]),
  D("Ofenkäse mit Baguette", "Gutbürgerlich", "leicht", 20, "v", ["1 Backcamembert", "1 Baguette", "Honig", "Walnüsse", "Rosmarin", "Feldsalat"]),
  D("Belegte Brote mit Radieschenquark", "Gutbürgerlich", "schnell", 15, "vkp", ["1 Laib Vollkornbrot", "500 g Quark", "1 Bund Radieschen", "Schnittlauch", "Butter", "1 Salatgurke"]),
  D("Käseplatte mit Trauben und Baguette", "Gutbürgerlich", "leicht", 15, "vk", ["3 Sorten Käse", "1 Baguette", "Weintrauben", "Walnüsse", "Feigensenf", "Butter"]),

  /* ---------------- Asiatisch ---------------- */
  D("Sushi selbst rollen", "Japanisch", "neu", 50, "s", ["300 g Sushireis", "Reisessig & Zucker", "5 Nori-Blätter", "200 g Lachs in Sashimi-Qualität", "1 Salatgurke", "1 Avocado", "Sojasauce & Wasabi"], "Bambusmatte in Frischhaltefolie wickeln – spart das Schrubben."),
  D("Chicken Teriyaki mit Reis", "Japanisch", "schnell", 25, "f", ["2 Hähnchenschenkel ohne Knochen", "4 EL Sojasauce", "3 EL Mirin", "1 EL Zucker", "150 g Reis", "Frühlingszwiebel", "Sesam"]),
  D("Katsu Curry", "Japanisch", "komfort", 45, "f", ["2 Hähnchenbrustfilets", "Panko", "2 Eier", "1 Packung japanische Curryblöcke", "2 Karotten", "1 Kartoffel", "150 g Reis"]),
  D("Yakisoba", "Japanisch", "schnell", 20, "f", ["300 g Yakisoba-Nudeln", "200 g Schweinebauch in Streifen", "1/4 Weißkohl", "1 Karotte", "4 EL Yakisoba-Sauce", "Frühlingszwiebel"]),
  D("Miso-Suppe mit Tofu und Udon", "Japanisch", "leicht", 20, "v", ["1 l Dashi oder Gemüsebrühe", "3 EL Miso", "200 g Tofu", "300 g Udon", "1 Frühlingszwiebel", "Wakame"]),
  D("Karaage – japanisches Brathähnchen", "Japanisch", "neu", 40, "f", ["600 g Hähnchenschenkelfleisch", "4 EL Sojasauce", "Ingwer & Knoblauch", "100 g Speisestärke", "Frittieröl", "1 Zitrone", "Reis"]),
  D("Gyoza mit Dip", "Japanisch", "neu", 45, "f", ["30 Gyoza-Teigblätter", "300 g Schweinehack", "1/4 Chinakohl", "Ingwer & Knoblauch", "Sesamöl", "Sojasauce & Reisessig"], "Braten, dann Wasser dazu und Deckel drauf – knusprig unten, zart oben."),
  D("Bibimbap", "Koreanisch", "neu", 35, "fx", ["150 g Reis", "300 g Rinderhack", "1 Karotte", "150 g Spinat", "150 g Sojasprossen", "2 Eier", "3 EL Gochujang", "Sesamöl"]),
  D("Bulgogi-Bowl", "Koreanisch", "komfort", 30, "f", ["400 g dünn geschnittenes Rindfleisch", "1 Birne", "5 EL Sojasauce", "Sesamöl", "Knoblauch", "150 g Reis", "Kimchi"]),
  D("Kimchi Fried Rice", "Koreanisch", "schnell", 20, "vpx", ["400 g Reis vom Vortag", "200 g Kimchi", "2 Eier", "1 EL Gochujang", "Frühlingszwiebel", "Sesamöl"]),
  D("Pad Thai", "Thai", "schnell", 25, "s", ["250 g Reisbandnudeln", "200 g Garnelen", "2 Eier", "150 g Sojasprossen", "3 EL Tamarindenpaste", "Erdnüsse", "Limette", "Fischsauce"]),
  D("Grünes Thai-Curry mit Hähnchen", "Thai", "komfort", 30, "fx", ["400 g Hähnchenbrust", "3 EL grüne Currypaste", "400 ml Kokosmilch", "1 Zucchini", "Thai-Basilikum", "150 g Jasminreis", "Limette"]),
  D("Massaman Curry mit Rind", "Thai", "komfort", 45, "f", ["500 g Rindfleisch", "3 EL Massaman-Paste", "400 ml Kokosmilch", "2 Kartoffeln", "Erdnüsse", "150 g Reis"]),
  D("Tom Kha Gai", "Thai", "leicht", 30, "f", ["300 g Hähnchenbrust", "400 ml Kokosmilch", "500 ml Hühnerbrühe", "Galgant & Zitronengras", "Champignons", "Limette", "Koriander"]),
  D("Pho Bo", "Vietnamesisch", "komfort", 60, "f", ["1,5 l Rinderbrühe", "Sternanis, Zimt, Nelken", "300 g Rinderfilet hauchdünn", "250 g Reisbandnudeln", "Sojasprossen", "Koriander & Thai-Basilikum", "Limette"]),
  D("Erdnuss-Sesam-Nudeln (kalt)", "Asiatisch", "leicht", 20, "vk", ["250 g Mie-Nudeln", "3 EL Erdnussbutter", "2 EL Sojasauce", "1 EL Reisessig", "Sesamöl", "1 Salatgurke", "Frühlingszwiebel"]),
  D("Poke Bowl mit Lachs", "Asiatisch", "leicht", 25, "sk", ["300 g Lachsfilet in Sashimi-Qualität", "200 g Sushireis", "1 Avocado", "1 Mango", "Edamame", "Sojasauce & Sesamöl", "Sesam"]),
  D("Chicken Tikka Masala mit Naan", "Indisch", "komfort", 40, "fx", ["500 g Hähnchenbrust", "200 g Joghurt", "3 EL Tikka-Gewürz", "400 g passierte Tomaten", "200 ml Sahne", "2 Naanbrote", "Koriander"]),
  D("Butter Chicken", "Indisch", "komfort", 40, "f", ["500 g Hähnchenschenkel", "400 g Tomaten", "100 g Butter", "150 ml Sahne", "Garam Masala", "Ingwer & Knoblauch", "150 g Basmatireis"]),
  D("Dal mit Reis und Joghurt", "Indisch", "leicht", 35, "vp", ["250 g rote Linsen", "1 Dose Tomaten", "1 Zwiebel", "Kurkuma, Kreuzkümmel, Garam Masala", "150 g Basmatireis", "Joghurt", "Koriander"]),
  D("Palak Paneer", "Indisch", "komfort", 35, "v", ["500 g Blattspinat", "250 g Paneer oder Halloumi", "1 Zwiebel", "Ingwer & Knoblauch", "100 ml Sahne", "Garam Masala", "Basmatireis"]),
  D("Linsen-Kokos-Curry", "Indisch", "leicht", 30, "vp", ["200 g rote Linsen", "400 ml Kokosmilch", "1 Dose Tomaten", "2 EL Currypulver", "1 Süßkartoffel", "Spinat", "Reis"]),
  D("Süßsauer-Hähnchen mit Reis", "Chinesisch", "schnell", 30, "f", ["400 g Hähnchenbrust", "1 Paprika", "1 Dose Ananas", "3 EL Ketchup", "2 EL Reisessig", "1 EL Sojasauce", "150 g Reis", "Speisestärke"]),
  D("Rindfleisch mit Brokkoli aus dem Wok", "Chinesisch", "schnell", 20, "f", ["350 g Rinderstreifen", "1 Brokkoli", "3 EL Austernsauce", "2 EL Sojasauce", "Ingwer & Knoblauch", "Speisestärke", "150 g Reis"]),
  D("Gebratene Nudeln mit Ei und Gemüse", "Chinesisch", "schnell", 20, "vp", ["250 g Mie-Nudeln", "3 Eier", "1 Karotte", "1/4 Weißkohl", "3 EL Sojasauce", "Sesamöl", "Frühlingszwiebel"]),
  D("Wan-Tan-Suppe", "Chinesisch", "leicht", 30, "f", ["20 Wan-Tan-Blätter", "250 g Schweinehack", "Ingwer & Frühlingszwiebel", "1,2 l Hühnerbrühe", "Pak Choi", "Sesamöl"]),
  D("Nasi Goreng", "Asiatisch", "schnell", 25, "fpx", ["400 g Reis vom Vortag", "200 g Hähnchen", "2 Eier", "1 Zwiebel", "2 EL Ketjap Manis", "Sambal Oelek", "Röstzwiebeln"]),
  D("Chicken Satay mit Erdnusssauce", "Thai", "neu", 35, "f", ["500 g Hähnchenbrust", "Holzspieße", "200 ml Kokosmilch", "4 EL Erdnussbutter", "Currypulver", "Limette", "Reis"]),
  D("Tempura-Gemüse mit Dip", "Japanisch", "neu", 40, "v", ["1 Süßkartoffel", "1 Zucchini", "150 g Tempuramehl", "eiskaltes Wasser", "Frittieröl", "Sojasauce & Mirin für den Dip", "Reis"]),
  D("Udon-Nudeln mit Gemüse", "Japanisch", "schnell", 20, "v", ["300 g Udon", "1 Karotte", "1 Pak Choi", "3 EL Sojasauce", "1 EL Mirin", "Sesamöl", "Frühlingszwiebel"]),
  D("Zoodles mit Garnelen", "Asiatisch", "leicht", 20, "sx", ["3 Zucchini", "300 g Garnelen", "1 Chili", "2 Knoblauchzehen", "1 Limette", "Olivenöl", "Kirschtomaten"]),

  /* ---------------- Orient, Griechenland, Spanien ---------------- */
  D("Gyros mit Tzatziki und Pommes", "Griechisch", "komfort", 35, "f", ["600 g Schweinenacken in Streifen", "3 EL Gyrosgewürz", "1 Zwiebel", "500 g Joghurt", "1 Salatgurke", "2 Knoblauchzehen", "600 g TK-Pommes"], "Fleisch mindestens 30 Min marinieren, gern schon morgens."),
  D("Dürüm mit Hähnchen selbst gemacht", "Türkisch", "neu", 35, "fx", ["500 g Hähnchenbrust", "Dönergewürz", "4 große Wraps", "Eisbergsalat", "Tomate & Zwiebel", "Knoblauchsauce", "scharfe Sauce"]),
  D("Souvlaki-Spieße mit Zitronenreis", "Griechisch", "komfort", 35, "f", ["600 g Schweinefilet", "Oregano & Zitrone", "Holzspieße", "150 g Reis", "1 Zitrone", "Tzatziki", "Fladenbrot"]),
  D("Bifteki mit Feta", "Griechisch", "komfort", 40, "f", ["500 g Hackfleisch", "200 g Feta", "1 Zwiebel", "1 Ei", "Oregano", "800 g Kartoffeln für Ofenkartoffeln", "Tomatensalat"]),
  D("Moussaka", "Griechisch", "komfort", 75, "f", ["2 Auberginen", "500 g Lammhack", "400 g Tomaten", "500 ml Milch", "40 g Butter & Mehl", "150 g Käse", "Zimt"]),
  D("Griechischer Bauernsalat mit Pita", "Griechisch", "leicht", 15, "vk", ["4 Tomaten", "1 Salatgurke", "1 rote Zwiebel", "200 g Feta", "Oliven", "Oregano & Olivenöl", "4 Pitabrote"]),
  D("Falafel mit Hummus und Fladenbrot", "Orientalisch", "leicht", 35, "v", ["1 Dose Kichererbsen", "1 Zwiebel", "Petersilie & Koriander", "2 EL Mehl", "Tahini", "1 Zitrone", "Fladenbrot", "Frittieröl"]),
  D("Hummus-Bowl mit Ofengemüse", "Orientalisch", "leicht", 40, "v", ["1 Dose Kichererbsen", "3 EL Tahini", "1 Zitrone", "1 Aubergine", "2 Paprika", "Granatapfelkerne", "Fladenbrot"]),
  D("Shakshuka", "Orientalisch", "schnell", 25, "vpx", ["800 g stückige Tomaten", "2 Paprika", "1 Zwiebel", "4 Eier", "Kreuzkümmel & Paprikapulver", "Feta", "Fladenbrot"], "Eier in Mulden schlagen, Deckel drauf, 6 Minuten – Eigelb bleibt weich."),
  D("Köfte mit Bulgursalat", "Türkisch", "komfort", 35, "f", ["500 g Lamm- oder Rinderhack", "1 Zwiebel", "Petersilie", "Kreuzkümmel", "200 g Bulgur", "Tomaten & Gurke", "Joghurtdip"]),
  D("Lahmacun vom Blech", "Türkisch", "schnell", 30, "fx", ["4 fertige Lahmacun-Böden oder Pizzateig", "300 g Lammhack", "1 Paprika", "2 EL Tomatenmark", "Petersilie", "Zitrone", "Salat"]),
  D("Börek mit Spinat und Schafskäse", "Türkisch", "komfort", 45, "v", ["1 Packung Yufka- oder Blätterteig", "500 g Blattspinat", "250 g Schafskäse", "2 Eier", "150 ml Milch", "Sesam"]),
  D("Mercimek – türkische Linsensuppe", "Türkisch", "leicht", 30, "vp", ["250 g rote Linsen", "1 Zwiebel", "1 Karotte", "1 EL Tomatenmark", "1,2 l Brühe", "Zitrone", "Minze & Paprikabutter"]),
  D("Couscous-Salat mit gegrilltem Gemüse", "Orientalisch", "leicht", 25, "vk", ["200 g Couscous", "1 Zucchini", "1 Paprika", "Kirschtomaten", "Minze & Petersilie", "Zitrone & Olivenöl", "Feta"]),
  D("Tajine mit Hähnchen und Aprikosen", "Orientalisch", "komfort", 60, "f", ["4 Hähnchenschenkel", "100 g getrocknete Aprikosen", "1 Dose Kichererbsen", "Ras el Hanout", "2 Zwiebeln", "Mandeln", "Couscous"]),
  D("Sucuk mit Ei und Fladenbrot", "Türkisch", "schnell", 15, "fp", ["200 g Sucuk", "4 Eier", "1 Fladenbrot", "Tomaten", "Petersilie"]),
  D("Paella mit Meeresfrüchten", "Spanisch", "komfort", 50, "s", ["300 g Paellareis", "400 g Meeresfrüchte", "1 Paprika", "TK-Erbsen", "Safran", "1 l Fischfond", "1 Zitrone"]),
  D("Tortilla Española mit Salat", "Spanisch", "schnell", 30, "vp", ["800 g Kartoffeln", "6 Eier", "2 Zwiebeln", "Olivenöl", "Blattsalat", "Aioli"]),
  D("Gambas al Ajillo mit Brot", "Spanisch", "leicht", 20, "sx", ["400 g Garnelen", "6 Knoblauchzehen", "2 Chilischoten", "100 ml Olivenöl", "Petersilie", "1 Baguette"]),
  D("Patatas Bravas & Tapas-Teller", "Spanisch", "leicht", 35, "vx", ["800 g Kartoffeln", "400 g passierte Tomaten", "Paprikapulver & Chili", "Aioli", "Oliven", "Manchego", "Baguette"]),
  D("Fisch aus dem Ofen mit Oliven und Tomaten", "Mediterran", "leicht", 35, "s", ["2 ganze Doraden oder 4 Filets", "400 g Kirschtomaten", "Oliven", "1 Zitrone", "Rosmarin", "600 g Kartoffeln", "Olivenöl"]),
  D("Zucchini-Feta-Puffer mit Joghurtdip", "Griechisch", "schnell", 30, "v", ["3 Zucchini", "200 g Feta", "2 Eier", "4 EL Mehl", "Minze", "250 g Joghurt", "1 Knoblauchzehe"]),
  D("Halloumi-Bowl mit Ofengemüse", "Mediterran", "leicht", 25, "v", ["250 g Halloumi", "1 Paprika", "1 Zucchini", "150 g Couscous", "Zitrone", "Minze", "Granatapfelkerne"]),
  D("Gazpacho mit Brot", "Spanisch", "leicht", 20, "vk", ["1 kg reife Tomaten", "1 Salatgurke", "1 Paprika", "1 Knoblauchzehe", "3 EL Olivenöl", "2 EL Sherryessig", "altbackenes Brot"]),

  /* ---------------- Streetfood, USA, Mexiko ---------------- */
  D("BigMac-Rolle", "Amerikanisch", "neu", 35, "f", ["1 Rolle Blätterteig", "500 g Rinderhack", "150 g Cheddar", "1 Zwiebel", "Essiggurken", "Eisbergsalat", "Burgersauce (Mayo, Ketchup, Senf, Gurkenrelish)", "Sesam"], "Salat und Sauce erst nach dem Backen dazu – sonst weicht alles durch."),
  D("Burger mit Süßkartoffelpommes", "Amerikanisch", "komfort", 40, "f", ["500 g Rinderhack", "4 Burgerbrötchen", "4 Scheiben Cheddar", "1 Süßkartoffel je Person", "Salat, Tomate, Zwiebel", "Burgersauce", "Essiggurken"]),
  D("Cheeseburger-Auflauf", "Amerikanisch", "komfort", 45, "f", ["500 g Rinderhack", "300 g Nudeln", "200 g Cheddar", "1 Zwiebel", "3 EL Ketchup & Senf", "Essiggurken", "200 ml Sahne"]),
  D("Pulled Pork Sandwich", "Amerikanisch", "komfort", 120, "f", ["1,2 kg Schweinenacken", "BBQ-Rub", "200 ml BBQ-Sauce", "4 Brioche-Buns", "1/2 Weißkohl für Coleslaw", "Mayonnaise & Essig"], "Läuft im Ofen von allein – gut für einen Abend mit Papierkram nebenher."),
  D("Hot Dogs mit Röstzwiebeln", "Amerikanisch", "schnell", 15, "fp", ["4 Hot-Dog-Würstchen", "4 Hot-Dog-Brötchen", "Röstzwiebeln", "Gurkenrelish", "Ketchup & Senf"]),
  D("Chili con Carne", "Mexikanisch", "komfort", 50, "fx", ["500 g Rinderhack", "1 Dose Kidneybohnen", "1 Dose Mais", "800 g Tomaten", "2 Paprika", "Chili & Kreuzkümmel", "1 Stück Zartbitterschokolade"], "Ein Stück dunkle Schokolade am Ende macht die Tiefe."),
  D("Chili sin Carne", "Mexikanisch", "komfort", 45, "vpx", ["1 Dose Kidneybohnen", "1 Dose schwarze Bohnen", "1 Dose Mais", "800 g Tomaten", "2 Paprika", "Räucherpaprika & Chili", "Reis"]),
  D("Tacos mit Hackfleisch", "Mexikanisch", "schnell", 25, "fx", ["8 Taco-Shells", "400 g Rinderhack", "1 Päckchen Taco-Gewürz", "Eisbergsalat", "Tomaten", "Cheddar", "Sauerrahm"]),
  D("Burrito-Bowl", "Mexikanisch", "schnell", 25, "f", ["150 g Reis", "400 g Hähnchenbrust", "1 Dose schwarze Bohnen", "1 Dose Mais", "1 Avocado", "Limette & Koriander", "Salsa"]),
  D("Quesadillas mit Bohnen und Käse", "Mexikanisch", "schnell", 20, "vp", ["6 Weizentortillas", "1 Dose schwarze Bohnen", "200 g geriebener Käse", "1 Paprika", "Frühlingszwiebel", "Sauerrahm"]),
  D("Enchiladas aus dem Ofen", "Mexikanisch", "komfort", 45, "fx", ["8 Tortillas", "500 g Hähnchen", "400 g Enchilada-Sauce", "1 Dose Bohnen", "200 g Käse", "Koriander"]),
  D("Nachos überbacken", "Mexikanisch", "schnell", 20, "vpx", ["200 g Tortilla-Chips", "1 Dose Kidneybohnen", "200 g Käse", "Jalapeños", "Guacamole", "Sauerrahm"]),
  D("Fajitas mit Paprika und Hähnchen", "Mexikanisch", "schnell", 30, "f", ["500 g Hähnchenbrust", "3 Paprika", "2 Zwiebeln", "Fajita-Gewürz", "8 Weizentortillas", "Sauerrahm", "Limette"]),
  D("Sloppy Joes", "Amerikanisch", "schnell", 25, "f", ["500 g Rinderhack", "4 Burgerbrötchen", "1 Paprika", "1 Zwiebel", "4 EL Ketchup", "1 EL Worcestersauce", "Cheddar"]),
  D("Caesar Salad mit Hähnchen", "Amerikanisch", "leicht", 25, "fk", ["2 Römersalate", "2 Hähnchenbrustfilets", "50 g Parmesan", "2 Sardellenfilets", "Mayonnaise & Zitrone", "Croutons"]),
  D("Cobb Salad", "Amerikanisch", "leicht", 20, "fk", ["Eisbergsalat", "2 hartgekochte Eier", "150 g Bacon", "1 Avocado", "Kirschtomaten", "100 g Blauschimmelkäse", "Joghurtdressing"]),
  D("Mac and Cheese", "Amerikanisch", "komfort", 30, "vp", ["300 g Makkaroni", "300 ml Milch", "200 g Cheddar", "30 g Butter & Mehl", "Senfpulver", "Semmelbrösel"]),
  D("Buffalo Wings mit Coleslaw", "Amerikanisch", "komfort", 45, "fx", ["1 kg Chicken Wings", "100 g Butter", "100 ml scharfe Sauce", "1/2 Weißkohl", "1 Karotte", "Mayonnaise & Essig", "Blauschimmeldip"]),
  D("Club Sandwich", "Amerikanisch", "schnell", 15, "fk", ["6 Scheiben Toast", "150 g Putenbrust", "4 Scheiben Bacon", "Tomate & Salat", "Mayonnaise", "1 Ei"]),
  D("Fish and Chips", "Amerikanisch", "komfort", 40, "s", ["500 g Kabeljaufilet", "150 g Mehl", "200 ml Bier", "800 g Kartoffeln", "Frittieröl", "Remoulade", "Zitrone"]),

  /* ---------------- Leicht & proteinbetont ---------------- */
  D("Protein Pizza", "Protein", "neu", 35, "v", ["250 g Magerquark", "250 g Mehl (oder Dinkelmehl)", "1 Päckchen Backpulver", "150 g passierte Tomaten", "150 g Mozzarella light", "Rucola", "Oregano"], "Quarkteig ohne Gehzeit – von der Schüssel bis zum Ofen sind es 8 Minuten."),
  D("Lachs mit Kartoffeln und Kräuterquark", "Protein", "leicht", 30, "s", ["2 Lachsfilets", "800 g Kartoffeln", "500 g Magerquark", "Schnittlauch & Dill", "1 Zitrone", "Olivenöl", "Blattsalat"], "Lachs bei 160 °C 15 Minuten – bleibt saftig statt trocken."),
  D("Hähnchenbrust mit Ofengemüse", "Protein", "leicht", 35, "f", ["2 Hähnchenbrustfilets", "2 Paprika", "1 Zucchini", "200 g Kirschtomaten", "Olivenöl", "Paprikapulver", "Feta"]),
  D("Putenstreifen mit Brokkoli und Reis", "Protein", "schnell", 25, "f", ["400 g Putenbrust", "1 Brokkoli", "150 g Reis", "2 EL Sojasauce", "Ingwer", "Sesam"]),
  D("Omelett mit Gemüse und Käse", "Protein", "schnell", 15, "vp", ["6 Eier", "1 Paprika", "100 g Champignons", "80 g geriebener Käse", "Schnittlauch", "Butter"]),
  D("Rührei mit Räucherlachs und Avocado", "Protein", "schnell", 15, "s", ["6 Eier", "150 g Räucherlachs", "1 Avocado", "4 Scheiben Vollkornbrot", "Schnittlauch", "Butter"]),
  D("Thunfisch-Bowl mit Reis und Edamame", "Protein", "leicht", 20, "sp", ["2 Dosen Thunfisch", "200 g Reis", "150 g Edamame", "1 Karotte", "Sojasauce & Sesamöl", "Frühlingszwiebel"]),
  D("Hüttenkäse-Wraps mit Putenbrust", "Protein", "schnell", 10, "fkp", ["4 Wraps", "400 g Hüttenkäse", "200 g Putenbrust", "Salat & Tomate", "Senf", "Schnittlauch"]),
  D("Linsensalat mit Feta", "Protein", "leicht", 25, "vk", ["250 g Beluga-Linsen", "200 g Feta", "1 rote Zwiebel", "Kirschtomaten", "Petersilie", "Balsamico & Olivenöl"]),
  D("Skyr-Salat mit Ei und Kichererbsen", "Protein", "leicht", 20, "vk", ["300 g Skyr", "4 Eier", "1 Dose Kichererbsen", "Blattsalat", "1 Salatgurke", "Zitrone & Senf", "Dill"]),
  D("Blumenkohlreis-Pfanne mit Hähnchen", "Protein", "leicht", 25, "f", ["1 Blumenkohl", "400 g Hähnchenbrust", "1 Paprika", "2 Eier", "Sojasauce", "Frühlingszwiebel"]),
  D("Gefüllte Süßkartoffel mit Hüttenkäse", "Protein", "leicht", 50, "v", ["2 große Süßkartoffeln", "400 g Hüttenkäse", "1 Dose Kichererbsen", "Räucherpaprika", "Schnittlauch", "Olivenöl"]),
  D("Kabeljau mit Erbsenpüree", "Protein", "leicht", 30, "s", ["2 Kabeljaufilets", "400 g TK-Erbsen", "1 Zitrone", "Minze", "300 g Kartoffeln", "Butter"]),
  D("Garnelenspieße mit Salat", "Protein", "leicht", 25, "sk", ["400 g Garnelen", "Holzspieße", "Blattsalat", "Kirschtomaten", "1 Avocado", "Zitrone & Olivenöl", "Knoblauch"]),
  D("Gemüsepfanne mit Halloumi", "Protein", "schnell", 25, "v", ["250 g Halloumi", "1 Zucchini", "1 Paprika", "200 g Kirschtomaten", "1 rote Zwiebel", "Olivenöl", "Oregano"]),
  D("Grillgemüse mit Kräuterquark", "Protein", "leicht", 30, "v", ["2 Zucchini", "2 Paprika", "1 Aubergine", "500 g Magerquark", "Kräuter", "Olivenöl", "Fladenbrot"]),
  D("Quinoa-Bowl mit Ofengemüse", "Protein", "leicht", 40, "v", ["200 g Quinoa", "1 Süßkartoffel", "1 Brokkoli", "1 Dose Kichererbsen", "Tahini-Dressing", "Granatapfelkerne"]),
  D("Abend-Bowl mit Magerquark und Beeren", "Protein", "schnell", 10, "vkp", ["500 g Magerquark", "200 g Beeren", "2 EL Haferflocken", "1 EL Nüsse", "1 TL Honig"], "Wenn der Tag zu lang war und der Herd zu weit weg ist."),

  /* ---------------- Suppen & Kaltes ---------------- */
  D("Tomatensuppe mit Croutons", "Gutbürgerlich", "schnell", 25, "vp", ["800 g stückige Tomaten", "1 Zwiebel", "500 ml Gemüsebrühe", "100 ml Sahne", "Basilikum", "2 Scheiben Brot für Croutons"]),
  D("Kürbissuppe mit Kernöl", "Gutbürgerlich", "leicht", 35, "v", ["1 Hokkaidokürbis", "1 Zwiebel", "1 Stück Ingwer", "800 ml Brühe", "100 ml Kokosmilch", "Kürbiskernöl"]),
  D("Rösti mit Räucherlachs", "Gutbürgerlich", "schnell", 25, "s", ["800 g Kartoffeln", "150 g Räucherlachs", "200 g Schmand", "Dill", "1 Zitrone", "Butterschmalz"]),

  /* ---------------- Bestellen ---------------- */
  D("Burger-Lieferung", "Amerikanisch", "bestellen", 0, "fp", ["Ein Salat aus dem Kühlschrank dazu"], "Pommes immer separat bestellen – sie überleben den Transport besser."),
  D("Indisch bestellen", "Indisch", "bestellen", 0, "fpx", ["Reis reicht meist für zwei Currys"], "Ein mildes und ein scharfes Curry teilen."),
  D("Vietnamesisch bestellen", "Vietnamesisch", "bestellen", 0, "fp", ["Nichts – höchstens Limetten und frische Kräuter"]),
  D("Griechischer Grillteller", "Griechisch", "bestellen", 0, "fp", ["Tzatziki reicht oft nicht – ein zweites bestellen"]),

  /* ---------------- Alltagsklassiker ---------------- */
  D("Nudeln mit Tomatensoße", "Italienisch", "schnell", 20, "vp", ["250 g Nudeln", "700 g passierte Tomaten", "1 Zwiebel", "1 Knoblauchzehe", "Basilikum", "Parmesan", "1 TL Zucker"]),
  D("Hühnerfrikassee mit Reis", "Gutbürgerlich", "komfort", 45, "f", ["500 g Hähnchenbrust", "1 Glas Spargel", "150 g Champignons", "TK-Erbsen", "40 g Butter & Mehl", "200 ml Sahne", "150 g Reis", "1 Zitrone"]),
  D("Hackbällchen in Tomatensoße mit Reis", "Gutbürgerlich", "komfort", 35, "f", ["500 g Hackfleisch", "1 Brötchen", "1 Ei", "700 g passierte Tomaten", "1 Zwiebel", "150 g Reis", "Oregano"]),
  D("Semmelknödel mit Pilzrahmsoße", "Gutbürgerlich", "komfort", 40, "v", ["6 Semmelknödel", "400 g gemischte Pilze", "1 Zwiebel", "200 ml Sahne", "Petersilie", "Gemüsebrühe"]),
  D("Feta-Pasta aus dem Ofen", "Mediterran", "schnell", 30, "v", ["200 g Feta am Stück", "500 g Kirschtomaten", "250 g Nudeln", "4 EL Olivenöl", "2 Knoblauchzehen", "Basilikum"], "Feta in die Mitte, Tomaten drumherum, 25 Min bei 200 °C – dann verrühren."),
  D("Ofen-Frittata mit Kartoffeln", "Italienisch", "schnell", 30, "vp", ["8 Eier", "600 g gekochte Kartoffeln", "1 Zucchini", "100 g geriebener Käse", "1 Zwiebel", "Kräuter"]),
  D("Forelle Müllerin mit Petersilienkartoffeln", "Gutbürgerlich", "komfort", 35, "s", ["2 Forellen", "100 g Mehl", "80 g Butter", "1 Zitrone", "800 g Kartoffeln", "Petersilie", "Mandelblättchen"]),
  D("Fischfilet in Senfsoße mit Kartoffeln", "Gutbürgerlich", "leicht", 35, "s", ["400 g Seelachsfilet", "2 EL mittelscharfer Senf", "200 ml Sahne", "1 Zwiebel", "700 g Kartoffeln", "Dill", "Gemüsebrühe"]),
  D("Bratwurst mit Kartoffelsalat", "Gutbürgerlich", "schnell", 30, "fp", ["4 Bratwürste", "800 g Kartoffeln", "1 Zwiebel", "200 ml Brühe", "Essig, Öl, Senf", "Schnittlauch"]),
  D("Grillabend mit Steak und Salaten", "Gutbürgerlich", "komfort", 60, "f", ["2 Steaks", "4 Bratwürste", "Grillgemüse", "Kartoffelsalat", "Krautsalat", "Baguette", "Kräuterbutter"]),
  D("Raclette-Abend", "Gutbürgerlich", "komfort", 60, "f", ["400 g Raclettekäse", "1 kg kleine Kartoffeln", "Schinken & Salami", "Champignons", "Paprika & Mais", "Essiggurken", "Baguette"], "Kartoffeln vorher kochen – der Rest passiert am Tisch."),
  D("Hähnchen-Nuggets selbst gemacht mit Pommes", "Amerikanisch", "komfort", 40, "f", ["600 g Hähnchenbrust", "2 Eier", "150 g Cornflakes oder Panko", "100 g Mehl", "600 g TK-Pommes", "Ketchup & Honig-Senf-Dip"]),
  D("Pizzabrot mit Kräuterbutter", "Italienisch", "schnell", 20, "vp", ["1 Pizzateig oder Baguette", "100 g Butter", "3 Knoblauchzehen", "Petersilie", "100 g Mozzarella", "Blattsalat"]),
  D("Chicken Wraps", "Amerikanisch", "schnell", 20, "f", ["400 g Hähnchenbrust", "4 Wraps", "Eisbergsalat", "1 Tomate", "Joghurt-Knoblauch-Sauce", "Paprikapulver", "Cheddar"]),
  D("Ofengemüse mit Feta und Fladenbrot", "Mediterran", "leicht", 40, "v", ["1 Aubergine", "2 Paprika", "1 Zucchini", "1 rote Zwiebel", "200 g Feta", "Olivenöl & Oregano", "Fladenbrot"]),
  D("Reispfanne mit Gemüse und Ei", "Asiatisch", "schnell", 20, "vp", ["300 g Reis", "1 Karotte", "1 Paprika", "TK-Erbsen", "3 Eier", "Sojasauce", "Frühlingszwiebel"]),
  D("Wurstgulasch mit Nudeln", "Gutbürgerlich", "schnell", 25, "fp", ["300 g Fleischwurst", "2 Zwiebeln", "2 EL Tomatenmark", "1 EL Paprikapulver", "250 g Nudeln", "Brühe", "Schmand"]),
  D("Spinat-Ricotta-Cannelloni", "Italienisch", "komfort", 55, "v", ["16 Cannelloni", "500 g Blattspinat", "250 g Ricotta", "700 g passierte Tomaten", "150 g geriebener Käse", "Muskat", "Knoblauch"]),

  /* ---------------- Fast Food ---------------- */
  D("McDonald's", "Amerikanisch", "bestellen", 0, "fp", ["Nichts – höchstens ein paar Gurkenscheiben für zu Hause"], "Über die App bestellen, dort gibt es fast immer einen Gutschein."),
  D("Burger King", "Amerikanisch", "bestellen", 0, "fp", ["Ein grüner Salat dazu macht es erträglicher"]),
  D("Subway", "Amerikanisch", "bestellen", 0, "fvp", ["Nichts weiter nötig"], "Footlong teilen statt zwei Sixinch – gleiche Menge, weniger Geld."),
  D("Asia Wok", "Asiatisch", "bestellen", 0, "fpx", ["Ein extra Reis reicht meist für zwei Gerichte"], "Zwei Gerichte teilen ist fast immer besser als je eins."),
].map((d, i) => ({ ...d, id: 1000 + i }));

export const DISHES = [...CORE, ...EXTRA];
